name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          cd carservice
          ./gradlew build
          docker build -f ./Dockerfile -t local/carservice .
          echo -n "verifying images:"
          docker images
          cd ..
      - name: Deploy to minikube
        run:
          kubectl apply -f deploymentaction.yaml
      - name: Get service URL
        run: |
          kubectl get pods
          minikube service list
          minikube service carservice --url
          echo "------------------opening the service------------------"
      - name: Test service URL
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 3
          command: curl $(minikube service carservice --url)/cars